### ISSUE TITLE
Proof headers are not sent, even by tests in the ProofKeys group

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/wopi-validator-core#84] opened 2019-10-30 17:16 UTC
The `X-WOPI-Proof` and `X-WOPI-ProofOld` headers are never sent by the validator. How can we validate the requests without them? The ProofKeys tests are meaningless if they don't send those headers...

**Comment by tylerbutler** [comment] 2019-12-12 20:29
Duplicate of #22.

**Closed by tylerbutler** 2019-12-12 20:29 UTC
Labels: duplicate
