### ISSUE TITLE
X-WOPI-Proof and X-WOPI-ProofOld not sended into http request

### ISSUE THREAD

**Issue by cesco69** [microsoft/wopi-validator-core#82] opened 2019-09-30 15:24 UTC
ProofKeys section of tests fail because my server not receive the X-WOPI-Proof and X-WOPI-ProofOld HTTP headers.

**Step for reproduce**

1. clone this repo and compiled into exe with Visual Studio 2015.

2. run this command
```sh
Microsoft.Office.WopiValidator.exe -t MYTOKEN -l 0 -w http://localhost:3000/api/wopi/files/5d8488e930a07d2218d89d35  -e OfficeOnline -s -g ProofKeys
```

Test ProofKeys fails.

These are the received headers (only 2):
```
Authorization: Bearer eyJvIjoiQUU5RENGMTQ0MkNDMkUyM0ZBRUE2Mjk1MTg4NzI3QzgiLCJlIjoiRHROT2NHQ2o4NFM1TVhMVkU4VVlqeVNoWmp1cHFtbGMiLCJpIjoiNWQ4NDg4ZTkzMGEwN2QyMjE4ZDg5ZDM1In0=
Host: localhost:3000
```

no X-WOPI-Proof and X-WOPI-ProofOld headers.

What i'm doing wrong?

**Comment by tylerbutler** [comment] 2019-10-02 11:01
Duplicate of #22.

**Closed by tylerbutler** 2019-10-02 11:01 UTC
